apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws-async-through-ingress-gateway
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway-ws-async
  http:
    - match:
        - uri:
            prefix: /ws
#          authority: #authority is used as workaround because of PORT presence in Host
#            prefix: "ws-async-app"
      route:
        - destination:
            port:
              number: 8080
            host: ws-async-app
